### ISSUE TITLE
项目接口导出后服务端进程报错后挂了

### ISSUE THREAD

**Issue by aleczhang** [sx1989827/DOClever#130]
打开项目，设置->导出，选择HTML格式，导出就会挂
> fs.js:167
    throw new ERR_INVALID_CALLBACK();
    ^
 TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:167:11)
    at Object.fs.unlink (fs.js:1036:14)
    at /export/github/DOClever/Server/routes/project/project.js:1735:36
    at FSReqWrap.oncomplete (fs.js:171:20)

根据 commit 253f733861694726fc027c3812f305bc67ec4d56 本地搭建服务测试的

node v10.4.1

**Comment by aleczhang** [comment]
`fs.unlink`
改成
`fs.unlinkSync`
就可以了
