### ISSUE TITLE
按照流程安装出错 求解

### ISSUE THREAD

**Issue by skylei** [sx1989827/DOClever#136]
![image](https://user-images.githubusercontent.com/1855591/50447804-b16d1980-0958-11e9-8fc3-fa7a6a01de9a.png)

**Comment by skylei** [comment]
mongodb:3.2依然报这个错误
![image](https://user-images.githubusercontent.com/1855591/50448733-d1530c00-095d-11e9-9e1c-744093b7ddb8.png)

[root@localhost api_server]# node Server/bin/www 
请输入mongodb数据库地址（比如：mongodb://localhost:27017/DOClever)：mongodb://127.0.0.1:27017/api_server
(node:10261) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
连接成功
请输入DOClever上传文件路径（比如：/Users/Shared/DOClever）：/www/server/api_server/storage/uploads
目录创建成功
目录创建成功
请输入端口号（比如10000）：10169
数据更新中,请勿操作
(node:10261) UnhandledPromiseRejectionWarning: MongoError: no globalScriptEngine in $where parsing
    at queryCallback (/www/server/api_server/node_modules/mongodb-core/lib/cursor.js:247:25)
    at /www/server/api_server/node_modules/mongodb-core/lib/connection/pool.js:531:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:10261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cntlis** [comment]
你这个问题解决了吗？我也是这个错误
