### ISSUE TITLE
POST运行API提示：Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by thinkclaves** [sx1989827/DOClever#22]
`Cannot read property 'toLowerCase' of undefined

TypeError: Cannot read property 'toLowerCase' of undefined
    at onProxy (/home/tianhengrd/deploy/DOClever/Server/routes/proxy/proxy.js:153:28)
    at /home/tianhengrd/deploy/DOClever/Server/routes/proxy/proxy.js:214:5
    at Layer.handle [as handle_request] (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/layer.js:95:5)
    at /home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:330:12)
    at next (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:176:3)
    at router (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:312:13)
    at /home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:330:12)
    at next (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:271:10)
    at logger (/home/tianhengrd/deploy/DOClever/Server/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:312:13)
    at /home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:330:12)
    at next (/home/tianhengrd/deploy/DOClever/Server/node_modules/express/lib/router/index.js:271:10)`

**Comment by sx1989827** [comment]
官网的帮助中心里的疑难解答第一个就是关于怎么适配nginx的，你可以看一下~

**Comment by thinkclaves** [comment]
经过 @sx1989827 帮助，该问题已经解决。
原因：
因为DOClever在调试接口的时候会发送一些下划线开头的自定义http头部，而nginx默认会过滤掉这些头部，所以我们需要在nginx的配置文件中http或者server的配置项中添加underscores_in_headers on;允许在header的字段中带下划线，然后重启nginx即可

**Comment by thinkclaves** [comment]
经过 @sx1989827 帮助，该问题已经解决。
原因：
因为DOClever在调试接口的时候会发送一些下划线开头的自定义http头部，而nginx默认会过滤掉这些头部，所以我们需要在nginx的配置文件中http或者server的配置项中添加underscores_in_headers on;允许在header的字段中带下划线，然后重启nginx即可
