### ISSUE TITLE
mac Sierra，fibers/bin/darwin-x64-47/fibers.node` is missing

### ISSUE THREAD

**Issue by leoliuzcl** [sx1989827/DOClever#26]
ry running this to fix the issue: /usr/local/Cellar/node/5.10.1/bin/node /usr/local/soft/DOClever-4.0.1/Server/node_modules/fibers/build
/usr/local/soft/DOClever-4.0.1/Server/node_modules/fibers/fibers.js:20
	throw new Error('Missing binary. See message above.');
	^

Error: Missing binary. See message above.
    at Object.<anonymous> (/usr/local/soft/DOClever-4.0.1/Server/node_modules/fibers/fibers.js:20:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/soft/DOClever-4.0.1/Server/node_modules/asyncawait/src/fibers.js:1:75)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by sx1989827** [comment]
node版本高了  建议使用node 最新的lts版本

**Comment by lmule** [comment]
## fibers aa
