### ISSUE TITLE
关于连接的mongo需要验证的问题

### ISSUE THREAD

**Issue by okitasann** [sx1989827/DOClever#43]
对于需要账号密码的mongo数据库可以通过修改配置文件或者其他什么方式完成连接吗?
`Unhandled rejection MongoError: not authorized on DOClever to execute command { find: "infos", filter: {}, projection: {}, limit: 1, batchSize: 1, singleBatch: true }
    at Function.MongoError.create (/opt/node_webapp/DOClever/Server/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/opt/node_webapp/DOClever/Server/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /opt/node_webapp/DOClever/Server/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by sx1989827** [comment]
类似这样就可以：mongodb://username:password@mongo地址:port/数据库名称

**Comment by okitasann** [comment]
修改了之后遇到了这个问题,这是什么原因
`events.js:160
      throw er; // Unhandled 'error' event
      ^
MongoError: Authentication failed.
    at Function.MongoError.create (/opt/node_webapp/DOClever/Server/node_modules/mongodb-core/lib/error.js:31:11)
    at /opt/node_webapp/DOClever/Server/node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/opt/node_webapp/DOClever/Server/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/opt/node_webapp/DOClever/Server/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/opt/node_webapp/DOClever/Server/node_modules/mongodb-core/lib/connection/connection.js:319:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
`

**Comment by sx1989827** [comment]
你加下qq群: 611940610  可以在里面细聊~

**Comment by okitasann** [comment]
已经解决了是账号权限的问题
