### ISSUE TITLE
移除仓库里的node_modules

### ISSUE THREAD

**Issue by chekun** [sx1989827/DOClever#8]
这个太大了，packages.json写好依赖就好了额 😄

感谢开源 ❤️

**Comment by sx1989827** [comment]
谢谢支持，是这样的，本来我也想移除，但是很多人不懂node，不知道怎么装依赖，而且很多人是内网环境，装不了，所以就没有移除node_modules了

**Comment by chekun** [comment]
@sx1989827 可以这样，单独把node_modules打包放在releases里面，这样两者都方便 😃

**Comment by sx1989827** [comment]
恩 好的 下一个版本我来试着改进下~

**Comment by reggielee** [comment]
先把依赖都去掉吧！可以提供一个打包好的，给那些不会用的人。这个工程太大了不利于贡献代码！
以后可以考虑把后端代码也压缩成一个js文件。放到dist目录下面

**Comment by magicliang** [comment]
本来想开个 issue，看到这里有了就顺便发一下吧。

mac 下依赖不可用。
需要把 node_modules 删除掉再安装才可以用。
环境：
OS X 10.12.6
node 8.1.4
npm 5.4.1

症状：

$ node ./Server/bin/www
## There is an issue with `node-fibers` ##
`/Users/magicliang/Desktop/Programming/git/DOClever/Server/node_modules/fibers/bin/darwin-x64-57/fibers.node` is missing.

Try running this to fix the issue: /usr/local/Cellar/node/8.1.4/bin/node /Users/magicliang/Desktop/Programming/git/DOClever/Server/node_modules/fibers/build
/Users/magicliang/Desktop/Programming/git/DOClever/Server/node_modules/fibers/fibers.js:20
  throw new Error('Missing binary. See message above.');
  ^

Error: Missing binary. See message above.
    at Object.<anonymous> (/Users/magicliang/Desktop/Programming/git/DOClever/Server/node_modules/fibers/fibers.js:20:8)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/magicliang/Desktop/Programming/git/DOClever/Server/node_modules/asyncawait/src/fibers.js:1:75)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/magicliang/Desktop/Programming/git/DOClever/Server/node_modules/asyncawait/src/async/makeAsyncFunc.js:1:75)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by sx1989827** [comment]
@magicliang 你好 你这个问题是node版本高了  需要node最新的lts版本 和node_modules没关系的

**Comment by magicliang** [comment]
了解了。
建议在文档里注明不要使用 Latest Current，以免有人遇到和我一样的问题。
