### ISSUE TITLE
线下部署安装出错

### ISSUE THREAD

**Issue by flyncn** [sx1989827/DOClever#94]
node Server/bin/www
数据更新中,请勿操作
Unhandled rejection MongoError: no globalScriptEngine in $where parsing
    at queryCallback (/www/wwwroot/doclever/Server/node_modules/mongodb-core/lib/cursor.js:223:25)
    at /www/wwwroot/doclever/Server/node_modules/mongodb-core/lib/connection/pool.js:541:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by flyncn** [comment]
环境centos7 + node 8.11.2 + mongodb 3.6.2

**Comment by hodgevk** [comment]
我也是同样错误，把mongodb降级就可以了

**Comment by soliyell** [comment]
找到问题了，可能是数据不兼容造成的
我新建一个库就可以正常部署了，但是旧数据怎么导入也是个问题

**Comment by DT-Kim** [comment]
我是通过设置mongDB启用JavaScript解决的。
应该是数据库初始化需要用到JavaScript，而服务器安装的时候默认禁止了JavaScript
